baseURL = 'http://munirmahedi-paviwala.github.io/'
languageCode = 'en-us'
title = "Munirmahedi Paviwala"
theme = "cactus"

[params]
  colortheme = "white" # dark, light, white, or classic

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All timelines"
url = "/timelines"
weight = 2

[[menu.main]]
name = "CV"
url = "/cv"
weight = 3

[[menu.main]]
name = "Research"
url = "/research"
weight = 4


